# Generated by Django 2.2.5 on 2020-03-18 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200318_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=50)),
                ('total_days', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('max_altitude', models.CharField(max_length=50)),
                ('best_season', models.CharField(max_length=80)),
                ('img', models.ImageField(upload_to='Package_Images/')),
                ('difficulty', models.CharField(max_length=20)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Company')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TourGuide')),
            ],
        ),
    ]
