# Generated by Django 2.2.5 on 2020-03-18 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('destination_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=50)),
                ('package_destination', models.ManyToManyField(to='home.Packages')),
            ],
        ),
        migrations.CreateModel(
            name='PackagePlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=20)),
                ('difficulty_level', models.CharField(max_length=50)),
                ('travel_details', models.CharField(max_length=40)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Packages')),
            ],
            options={
                'unique_together': {('plan_id', 'package_id')},
            },
        ),
    ]
