# Generated by Django 2.2.5 on 2020-03-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_destination_packageplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('activities_id', models.AutoField(primary_key=True, serialize=False)),
                ('activities', models.CharField(max_length=80)),
                ('travel_mode', models.CharField(max_length=50)),
            ],
        ),
    ]
