# Generated by Django 2.2.5 on 2020-03-18 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageActivities',
            fields=[
                ('package_activities_id', models.AutoField(primary_key=True, serialize=False)),
                ('activities_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Activities')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Packages')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.PackagePlan')),
            ],
            options={
                'unique_together': {('package_activities_id', 'package_id', 'plan_id', 'activities_id')},
            },
        ),
    ]
