# Generated by Django 2.2.5 on 2020-03-18 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_packageactivities'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('package_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='packages',
            name='overview',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packages',
            name='package_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.PackageType'),
            preserve_default=False,
        ),
    ]
