# Generated by Django 2.2.5 on 2020-03-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200318_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_img',
            field=models.ImageField(default=1, upload_to='Package_Images/'),
            preserve_default=False,
        ),
    ]
