# Generated by Django 2.2.5 on 2020-03-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_staff_staff_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='activities',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='packageplan',
            name='travel_details',
            field=models.CharField(max_length=100),
        ),
    ]
