# Generated by Django 2.2.5 on 2020-03-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200318_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCostInfo',
            fields=[
                ('cost_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_details', models.CharField(max_length=200)),
                ('cost_type', models.CharField(choices=[('cost_included', 'CostIncluded'), ('cost_excluded', 'CostExcluded')], max_length=128)),
                ('package_cost', models.ManyToManyField(to='home.Packages')),
            ],
        ),
    ]
