# Generated by Django 2.2.5 on 2020-03-20 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_packagecostinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_by', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=60)),
                ('review_date', models.DateField()),
                ('review', models.TextField()),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Packages')),
            ],
        ),
    ]
