# Generated by Django 2.2.5 on 2020-03-29 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_packagereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='staff_id',
        ),
        migrations.DeleteModel(
            name='TourGuide',
        ),
    ]
