# Generated by Django 2.2.5 on 2020-03-20 16:34

import compositefk.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200320_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourguide',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='tourguide',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourguide',
            name='staff',
            field=compositefk.fields.CompositeForeignKey(default=1, null_if_equal=[], on_delete=django.db.models.deletion.CASCADE, to='home.Staff', to_fields={'staff_id': compositefk.fields.LocalFieldValue('staff_details')}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourguide',
            name='staff_details',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
