# Generated by Django 2.2.5 on 2020-03-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200329_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='staff_id',
            field=models.ManyToManyField(to='home.Staff'),
        ),
    ]
