# Generated by Django 2.2.5 on 2020-03-20 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200320_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourguide',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tourguide',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='tourguide',
            name='staff_details',
        ),
        migrations.AddField(
            model_name='tourguide',
            name='staff_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.Staff'),
            preserve_default=False,
        ),
    ]
