# Generated by Django 2.2.5 on 2020-03-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_packages_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='staff_id',
            field=models.ManyToManyField(default=1, to='home.Staff'),
        ),
    ]
