# Generated by Django 2.2.5 on 2020-03-20 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200320_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguide',
            name='guides_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourguide',
            name='staff_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Staff'),
        ),
    ]
