# Generated by Django 2.2.5 on 2020-03-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_packages_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='staff_id',
            field=models.ManyToManyField(blank=True, default=1, null=True, to='home.Staff'),
        ),
    ]
