# Generated by Django 2.2.5 on 2020-03-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200329_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
