# Generated by Django 2.2.5 on 2020-03-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200320_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourguide',
            name='guides_id',
        ),
        migrations.AddField(
            model_name='tourguide',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
