# Generated by Django 2.2.5 on 2020-03-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_packages_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=50), max_length=255),
        ),
    ]
