# Generated by Django 2.2.5 on 2020-03-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200320_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourguide',
            name='staff_id',
        ),
    ]
