# Generated by Django 2.2.5 on 2020-03-20 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_tourguide_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourguide',
            name='id',
        ),
        migrations.AddField(
            model_name='tourguide',
            name='guides_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tourguide',
            name='staff_id',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='home.Staff'),
        ),
    ]
