# Generated by Django 2.2.5 on 2020-03-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200329_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='slug',
        ),
        migrations.AddField(
            model_name='packages',
            name='slug_field',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
