# Generated by Django 2.2.5 on 2020-03-20 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200320_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='staff_id',
        ),
        migrations.DeleteModel(
            name='TourGuide',
        ),
    ]
