# Generated by Django 2.2.5 on 2020-03-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200329_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagereview',
            name='ratings',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
