# Generated by Django 2.2.5 on 2020-03-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20200320_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourGuide',
            fields=[
                ('guides_id', models.AutoField(primary_key=True, serialize=False)),
                ('license_no', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=20)),
            ],
        ),
    ]
