# Generated by Django 2.2.5 on 2020-03-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_packagereview_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagereview',
            name='review_verification',
            field=models.BooleanField(default=True),
        ),
    ]
