# Generated by Django 2.2.5 on 2020-03-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_tourguide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TourGuide',
        ),
    ]
