# Generated by Django 2.2.5 on 2020-03-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_packagereview_review_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagereview',
            name='review_verification',
            field=models.BooleanField(default=False),
        ),
    ]
