# Generated by Django 2.2.5 on 2020-04-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20200408_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='staff_id',
        ),
    ]
