# Generated by Django 2.2.5 on 2020-03-20 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_tourguides'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TourGuides',
        ),
    ]
