# Generated by Django 2.2.5 on 2020-03-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_delete_tourguides'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='staff_id',
            field=models.ManyToManyField(to='home.Staff'),
        ),
    ]
