# Generated by Django 2.2.5 on 2020-03-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_packages_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='package_category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
