# Generated by Django 2.2.5 on 2020-03-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_packages_package_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='package_category',
        ),
    ]
