# Generated by Django 2.2.5 on 2020-03-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalTour',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('organization_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('total_people', models.IntegerField()),
                ('destination', models.CharField(max_length=200)),
                ('total_days', models.IntegerField()),
            ],
        ),
    ]
