# Generated by Django 2.2.5 on 2020-03-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_category', models.CharField(choices=[('adventure', 'Adventure'), ('trekking', 'Trekking'), ('activities', 'Activities'), ('cultural', 'Cultural')], max_length=128)),
                ('img', models.ImageField(upload_to='Package_Images/')),
            ],
        ),
    ]
