# Generated by Django 2.2.5 on 2020-03-25 16:19

from django.db import migrations, models
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0005_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizeTrip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_name', models.CharField(max_length=100)),
                ('adults', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('5+', '5+')], default=0, max_length=128)),
                ('children', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('5+', '5+')], default=0, max_length=128)),
                ('budget_per_person', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('package_type', multiselectfield.db.fields.MultiSelectField(choices=[('tour', 'Adventure'), ('trekking', 'Trekking'), ('mountain_biking', 'Mountain Biking'), ('peak_climbing', 'Peak Climbing'), ('mountain_flights', 'Mountain Flights'), ('short_treks', 'Short Treks'), ('paragliding', 'Paragliding'), ('jungle_safari', 'Jungle Safari'), ('day_tour', 'Day Tour'), ('bungee_jumping', 'Bungee Jumping')], max_length=122)),
                ('full_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('package_category', models.CharField(choices=[('first_class', 'First Class'), ('economy_class', 'Economy Class'), ('business_class', 'Business Class')], default=1, max_length=128)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer')], default=0, max_length=128)),
                ('message', models.TextField()),
            ],
        ),
    ]
