# Generated by Django 2.2.5 on 2020-03-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0006_customizetrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationaltour',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
