# Generated by Django 2.2.5 on 2020-03-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0007_auto_20200327_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizetrip',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
