# Generated by Django 2.2.5 on 2020-03-27 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_packages_package_category'),
        ('tourpackages', '0009_auto_20200327_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='request_package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Packages'),
            preserve_default=False,
        ),
    ]
