# Generated by Django 2.2.5 on 2020-03-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0010_auto_20200329_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug_field',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
