# Generated by Django 2.2.5 on 2020-03-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0011_blog_slug_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_package',
            field=models.CharField(default='abc', max_length=100),
        ),
    ]
