# Generated by Django 2.2.5 on 2020-03-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0012_booking_request_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='request_package',
        ),
    ]
