# Generated by Django 2.2.5 on 2020-03-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0013_remove_booking_request_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetInTouchRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=80)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customizetrip',
            name='email',
            field=models.EmailField(max_length=80),
        ),
    ]
