# Generated by Django 2.2.5 on 2020-04-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0013_auto_20200331_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_verification',
            field=models.BooleanField(default=False),
        ),
    ]
