# Generated by Django 2.2.5 on 2020-04-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0014_booking_booking_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='request_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
