# Generated by Django 2.2.5 on 2020-04-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0015_booking_request_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='selected_package',
            field=models.CharField(max_length=100),
        ),
    ]
