# Generated by Django 2.2.5 on 2020-04-20 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tourpackages', '0019_blog_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='request_user',
        ),
        migrations.AddField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
