# Generated by Django 2.2.5 on 2020-04-21 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackages', '0020_auto_20200420_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='selected_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Packages'),
        ),
    ]
