# Generated by Django 2.2.5 on 2020-03-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='airport_pickup',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=1, max_length=128),
            preserve_default=False,
        ),
    ]
