# Generated by Django 2.2.5 on 2020-03-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_booking_airport_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adults',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('5+', '5+')], default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='children',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('5+', '5+')], default=1, max_length=128),
            preserve_default=False,
        ),
    ]
