# Generated by Django 2.2.5 on 2020-03-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200321_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='package_category',
            field=models.CharField(choices=[('first_class', 'First Class'), ('economy_class', 'Economy Class'), ('business_class', 'Business Class')], default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer')], default=1, max_length=128),
            preserve_default=False,
        ),
    ]
