# Generated by Django 2.2.5 on 2020-03-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200321_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='airline',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='arrival_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='arrival_time',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='departure_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
