# Generated by Django 2.2.5 on 2020-03-21 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200321_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateField(default=datetime.date(2020, 3, 21)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_date',
            field=models.DateField(default=datetime.date(2020, 3, 21)),
        ),
    ]
