# Generated by Django 2.2.5 on 2020-03-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200321_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_date',
            field=models.DateField(),
        ),
    ]
