# Generated by Django 2.2.5 on 2020-03-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200321_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='departure_date',
        ),
    ]
