# Generated by Django 2.2.5 on 2020-03-21 09:18

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200321_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='adults',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('5+', '5+')], default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='booking',
            name='children',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('5+', '5+')], default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package_category',
            field=models.CharField(choices=[('first_class', 'First Class'), ('economy_class', 'Economy Class'), ('business_class', 'Business Class')], default=1, max_length=128),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer')], default=0, max_length=128),
        ),
    ]
