# Generated by Django 2.2.5 on 2020-04-08 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200321_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='country',
        ),
    ]
